### ISSUE TITLE
feature: Add vim path variable  completion support

### ISSUE THREAD

**Issue by krisfans** [LumaKernel/ddc-file#13]
Thanks for your work! 
Can you add vim variable path completion support?
For example, here's a path variable named `$VIM_PATH`, which is `let $VIM_PATH = fnamemodify(resolve(expand('<sfile>:p')), ':h:h')
`, I want to get completion infomation when I type `VIM_PATH/`, any idea for this? Thanks.

**Comment by Shougo** [comment]
It should be `$VIM_PATH/` instead of `VIM_PATH`.

**Comment by Shougo** [comment]
Please test #14.
